/* eslint-disable sort-keys */
export const HTML_TAGS = {
	A: 'a',
	ABBR: 'abbr',
	ADDRESS: 'address',
	AREA: 'area',
	ARTICLE: 'article',
	ASIDE: 'aside',
	AUDIO: 'audio',
	B: 'b',
	BASE: 'base',
	BDI: 'bdi',
	BDO: 'bdo',
	BLOCKQUOTE: 'blockquote',
	BODY: 'body',
	BR: 'br',
	BUTTON: 'button',
	CANVAS: 'canvas',
	CAPTION: 'caption',
	CITE: 'cite',
	CODE: 'code',
	COL: 'col',
	COLGROUP: 'colgroup',
	DATA: 'data',
	DATALIST: 'datalist',
	DD: 'dd',
	DEL: 'del',
	DETAILS: 'details',
	DFN: 'dfn',
	DIALOG: 'dialog',
	DIV: 'div',
	DL: 'dl',
	DT: 'dt',
	EM: 'em',
	EMBED: 'embed',
	FIELDSET: 'fieldset',
	FIGCAPTION: 'figcaption',
	FIGURE: 'figure',
	FOOTER: 'footer',
	FORM: 'form',
	H1: 'h1',
	H2: 'h2',
	H3: 'h3',
	H4: 'h4',
	H5: 'h5',
	H6: 'h6',
	HEAD: 'head',
	HEADER: 'header',
	HR: 'hr',
	HTML: 'html',
	I: 'i',
	IFRAME: 'iframe',
	IMG: 'img',
	INPUT: 'input',
	INS: 'ins',
	KBD: 'kbd',
	LABEL: 'label',
	LEGEND: 'legend',
	LI: 'li',
	LINK: 'link',
	MAIN: 'main',
	MAP: 'map',
	MARK: 'mark',
	META: 'meta',
	METER: 'meter',
	NAV: 'nav',
	NOSCRIPT: 'noscript',
	OBJECT: 'object',
	OL: 'ol',
	OPTGROUP: 'optgroup',
	OPTION: 'option',
	OUTPUT: 'output',
	P: 'p',
	PARAM: 'param',
	PICTURE: 'picture',
	PRE: 'pre',
	PROGRESS: 'progress',
	Q: 'q',
	RP: 'rp',
	RT: 'rt',
	RUBY: 'ruby',
	S: 's',
	SAMP: 'samp',
	SCRIPT: 'script',
	SECTION: 'section',
	SELECT: 'select',
	SMALL: 'small',
	SOURCE: 'source',
	SPAN: 'span',
	STRONG: 'strong',
	STYLE: 'style',
	SUB: 'sub',
	SUMMARY: 'summary',
	SUP: 'sup',
	SVG: 'svg',
	TABLE: 'table',
	TBODY: 'tbody',
	TD: 'td',
	TEMPLATE: 'template',
	TEXTAREA: 'textarea',
	TFOOT: 'tfoot',
	TH: 'th',
	THEAD: 'thead',
	TIME: 'time',
	TITLE: 'title',
	TR: 'tr',
	TRACK: 'track',
	U: 'u',
	UL: 'ul',
	VAR: 'var',
	VIDEO: 'video',
	WBR: 'wbr',
} as const;

export const HTML_INPUT_TYPES = {
	BUTTON: 'button',
	CHECKBOX: 'checkbox',
	COLOR: 'color',
	DATE: 'date',
	DATETIME: 'datetime',
	DATETIME_LOCAL: 'datetime-local',
	EMAIL: 'email',
	FILE: 'file',
	HIDDEN: 'hidden',
	IMAGE: 'image',
	MONTH: 'month',
	NUMBER: 'number',
	PASSWORD: 'password',
	RADIO: 'radio',
	RANGE: 'range',
	RESET: 'reset',
	SEARCH: 'search',
	SUBMIT: 'submit',
	TEL: 'tel',
	TEXT: 'text',
	TIME: 'time',
	URL: 'url',
	WEEK: 'week',
} as const;

export const SIZES = {
	XXS: 'xxs',
	XS: 'xs',
	SM: 'sm',
	MD: 'md',
	LG: 'lg',
	XL: 'xl',
	XXL: 'xxl',
} as const;

export const BREAKPOINTS = {
	XXS: 360,
	XS: 480,
	SM: 600,
	MD: 960,
	LG: 1280,
	XL: 1440,
	XXL: 1920,
} as const;

export const GRID_VALUES = {
	1: 1,
	2: 2,
	3: 3,
	4: 4,
	5: 5,
	6: 6,
	7: 7,
	8: 8,
	9: 9,
	10: 10,
	11: 11,
	12: 12,
} as const;

export const COLORS = {
	ERROR: 'error',
	INFO: 'info',
	PRIMARY: 'primary',
	SECONDARY: 'secondary',
	SUCCESS: 'success',
	TERTIARY: 'tertiary',
	WARNING: 'warning',
} as const;
